version: '3.7'

services:
  apache:
    build: './apache'
    restart: always
    ports:
      - 6666:80
    networks: 
      - frontend
      - backend
    volumes:
      - ./strony:/usr/local/apache2/htdocs

    depends_on:
      - php
      - mysql
  php:
    build: './php'
    restart: always
    networks: 
      - backend
    volumes:
      - ./strony:/usr/local/apache2/htdocs      
  mysql:
    build: './mysql'
    restart: always
    networks:
      - backend
    volumes:
      - ./Dane:/var/lib/mysql
networks: 
  backend:
  frontend:
